### ISSUE TITLE
JuJu OpenStack with Docker

### ISSUE THREAD

**Issue by emad-nk** [battlemidget/astokes.org#1]
Hi

I am new to juju openstack, before I was using devstack, so modifying conf files such as `nova.conf` was easy.

I was using devstack with nova-docker and also opendaylight integration. However devstack is not so stable and sometimes the connection between OpenDaylight and OpenStack breaks, which is cumbersome, so I decided to use more stable environment. In juju openstack I cannot find nova.conf to modify it and for example add `container_formats=ami,ari,aki,bare,ovf,ova,docker` that enables openstack glance to save docker format images.

Now I am using `Fully containerized openstack on single machine` so can you tell me how to make openstack capable of handling docker images? And If I want to integrate openstack with opendaylight I have to also modify `/etc/neutron/plugins/ml2/ml2_conf.ini` for example.

Any suggestion?

**Comment by adam-stokes** [comment]
This isn't the best place to ask this question, I suggest visiting askubuntu.com or ask.openstack.org. Anywhere here is a link discussing docker with openstack https://wiki.openstack.org/wiki/Docker

**Comment by emad-nk** [comment]
I asked the same question in the ask.ubuntu few days ago but nobody has responded yet.
